query GetCustomer($id: Int!) {
    customer(id: $id) {
        name
        country {
            ...CountryFieldFragment
        }
        currency {
            ...CurrencyFieldFragment
        }
    }
}
