query GetCountries($after: String) {
    countries(first: 20, after: $after) @paginate {
        edges {
            node {
                id
                name
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
        }
    }
}
